### ISSUE TITLE
게시글 이미지 로딩 방식

### ISSUE THREAD

**Issue by poap** [sparcs-kaist/dejavo#15]

**Comment by horknox** [comment]
현재는 jQuery fadeIn을 사용하고 있으며, vhmiddle을 통해 centered cropping 이 되도록 했습니다.

나중에 더 멋지게 바꾸도록 하죠. 지금은 이 이슈는 추상적이라 UI에 관한 논의를 마친 후에 구체적인 이슈를 따로 만드는 것으로 하겠습니다.
