### ISSUE TITLE
메인페이지 UI 수정

### ISSUE THREAD

**Issue by poap** [sparcs-kaist/dejavo#36]
https://slack-files.com/T024SHLFD-F04KRFWSN-f956bcc2b0

**Comment by daedoo** [comment]
병욱이형 서버 기준으로 메인페이지에 그림자 실종!

**Comment by daedoo** [comment]
첫번째 줄에 제목이 뜨지 않고 주최자 이름이 뜨고 있습니다

**Comment by daedoo** [comment]
Now의 색깔은 강조색 #f15050

**Comment by daedoo** [comment]
사진 클릭했을때만 이동하게 해주세요!

**Comment by horknox** [comment]
@daedoo sunguard 의견에 의하면 글을 클릭해도 이동하는게 좋을거 말했습니다. 좀 디베이팅이 있는거 같은데 한 번 고려해 주시기 바랍니다.
